export const notificationConstants = {
  NOTIFICATION_LOAD: "NOTIFICATION_LOAD",
  NOTIFICATION_SHOW: "NOTIFICATION_SHOW",
  NOTIFICATION_HIDE: "NOTIFICATION_HIDE",
  NOTIFICATION_EMPTY: "NOTIFICATION_EMPTY"
};
